HOST = "0.0.0.0"
PORT = 5000
LED_DATA_GPIO = 21
NUM_PIXELS = 150

SUNRISE_NUM_LEDS_PER_CYCLE = 15
SUNRISE_PHASE_1_RED_MAX_BRIGHTNESS = 2
SUNRISE_PHASE_1_WHITE_MAX_BRIGHTNESS = 5
SUNRISE_PHASE_1_TOTAL_MINUTES = 1.5

SUNRISE_PHASE_2_WHITE_MAX_BRIGHTNESS = 50
SUNRISE_PHASE_2_TOTAL_MINUTES = 1.5

SUNRISE_PHASE_3_WHITE_MAX_BRIGHTNESS = 255
SUNRISE_PHASE_3_TOTAL_MINUTES = 1.5




# GPIO pins for the rotary encoder
#ROTARY_CLK = 17
#ROTARY_DT = 18
ROTARY_SW = 26


# GPIO for the LED
LED_GPIO = 13
LED_GND = 14

USER = 'admin'
PASSWORD = 'password'
SECRET_KEY = 'your secret key here'